// Local storage stores data like the tokens generated by users

import { LoginResponse } from "../models/user.model";

const LOCAL_STORAGE_KEY = { // A variable that stores the object of the response (this case a token)
    token: "token"

}

export module localStorageUtils { //Create a LocalStorageUtils module to define what happens to the tokens

    export const writeToken = (token: string) => { //to write a new token, you pass the new token to write (replace)
        localStorage.setItem(LOCAL_STORAGE_KEY.token, token)
    }


    export const readToken = () => {
        localStorage.getItem(LOCAL_STORAGE_KEY.token)
    }


    export const deleteToken = () => {
        localStorage.removeItem(LOCAL_STORAGE_KEY.token)
    }
}