// Local storage stores data like the tokens generated by users

import { Token } from "@angular/compiler";
import { LoginResponse } from "../models/user.model";

const LOCAL_STORAGE_KEY = { // A variable that stores the object of the response (this case a token)
    token: "token",
    id: "id"
}

export module localStorageUtils { //Create a LocalStorageUtils module to define what happens to the tokens

    export const writeToken = (token: string) => { //to write a new token, you pass the new token to write (replace)
        localStorage.setItem(LOCAL_STORAGE_KEY.token, token)
    }


    export const readToken = ():string => {
        let token = localStorage.getItem(LOCAL_STORAGE_KEY.token)
        return token ? token : ""
    }


    export const deleteToken = () => {
        localStorage.removeItem(LOCAL_STORAGE_KEY.token)
    }

    export const writeId = (id: number) => {
        localStorage.setItem(LOCAL_STORAGE_KEY.id, JSON.stringify(id))
    }

    export const readId = (): number => {
        let id = localStorage.getItem(LOCAL_STORAGE_KEY.id)
        return id ? JSON.parse(id) : ""
    }

    export const delteId = () => {
        localStorage.removeItem(LOCAL_STORAGE_KEY.id)
    }
}